### ISSUE TITLE
Feature Request(s)

### ISSUE THREAD

**Issue by JuliXBR4VO** [Th3-AI/Th3-AI.github.io#5]
Hello Th3-C0der,
i love using DynaSpark AI. 
i think it has very big potential.
Here are some ideas to make it even better:
  - Websearch Feature
  - Writing-Animation (like ChatGPT)
  - An integration of Gemini Pro
    (because the ai sometimes makes mistakes
     or is not specific enough)

I hope i could help you! ;-)
JuliXBR4VO

**Comment by Th3-C0der** [comment]
Thanks for your kind words, JuliXBR4VO!
I really appreciate your suggestions and support for DynaSpark AI.

The web search feature is already in development.

I’ll also look into adding a nice typing animation soon.

As for Gemini Pro, I’ll try to add an option to let users select it. However, since I’m using a free Gemini API for now, I might provide an option for users to input their own API key if they prefer.


That said, it might take some time to implement these updates, as DynaSpark AI is a free-time project I’m working on. Since I’m a solo developer, balancing development with my studies can be challenging, so updates might be slower for a bit.

Thanks again for your support and patience!

**Comment by Th3-C0der** [comment]
On a side note, someone attempted a DoS attack on DynaSpark AI yesterday. This was the first time in 6 months that something like this happened, but everything is back to normal now.

By the way, if you don't mind me asking, how did you come to know about DynaSpark?

**Comment by JuliXBR4VO** [comment]
Hello Th3 C0der,
thanks for your feedback.
I mean it’s quiet cool that you are doing this alredy like the websearch feauture.
I was by the way looking on youtube to find out more about Gemini and then your video was displayed. I‘m thrilled to try the new features.

Best wishes, 
JuliXBR4VO

**Comment by JuliXBR4VO** [comment]
Hey its me again.
Just a proposal, but i have very good experiences
with Tavily AI. Maybe its an option for the
websearching feature for DynaSpark AI.
Good Luck!
JuliXBR4VO

**Comment by Th3-C0der** [comment]
Hey, Thanks a lot for your feedback, i really appreciate it....
I would definitely try Tavily AI, but it does have a monthly limit of 1000 api calls, so may be i will not consider it....

Implemented Features:- 
- [x] Typing Animation
- [x] Gemini Pro
   (You Can select between gemini-flash or gemini-pro in settings)(But you need your own API KEY to use gemini-pro)
- [x] Web Search
   (I use duckduckgo search engine for web searching)

**Comment by JuliXBR4VO** [comment]
Hey thank you sooooo much!
But i think Gemini 1.5 Pro API is free?

**Comment by JuliXBR4VO** [comment]
Here you can see it.

![Bild_2024-10-15_162557781](https://github.com/user-attachments/assets/2485ca7c-b05c-46fb-84ee-e55aaef87d47)

Here's the URL to the site: https://ai.google.dev/pricing#1_5pro

**Comment by Th3-C0der** [comment]
Yes the API is free just the thing is Gemini-Pro uses more tokens per responses
just create an api key and you can use it
https://aistudio.google.com/app/apikey

**Comment by Th3-C0der** [comment]
Yes, I know the Gemini pro API is free but it uses more tokens and has lower limits as compared to flash....
Flash:
![Screenshot 2024-10-15 200201](https://github.com/user-attachments/assets/47f9e80e-bdde-4d91-8b31-e44a95d67209)
Pro:
![Screenshot 2024-10-15 200210](https://github.com/user-attachments/assets/2aaa5a39-6890-44da-88fa-18eb2bcbae1f)

**Comment by JuliXBR4VO** [comment]
Hmm ok.
The problem is that I am living in Germany, so Google AI Studio isn't available here.
But i think this is just my problem.
Thank you instead of that. :-)

**Comment by Th3-C0der** [comment]
You're welcome, I didn't knew that Google AI Studio is not available in Germany, in that case if you want I can give you a Gemini API key, just contact/DM me on Instagram: https://instagram.com/th3_c0der

Best regards,
Th3-C0der

**Comment by JuliXBR4VO** [comment]
And whats about Gemini Pro 1.0 ?
I mean it has very equal limits like the Flash Model.

![Bild_2024-10-15_163729944](https://github.com/user-attachments/assets/a9a9bbef-787a-4464-a310-eaad4c57734a)

**Comment by JuliXBR4VO** [comment]
Sorry i cant send you messages. Your Profile is private.

**Comment by Th3-C0der** [comment]
Yes, 1.0 pro have similar limits to 1.5 flash, but 1.5 flash is way better than 1.0 pro....

Flash 1.5 has better multi modal capabilities than 1.0 pro.
1.0 pro was/is pretty bad as compared to latest models...

Here's a short reddit discussion on it:
https://www.reddit.com/r/Bard/comments/1d4wjz5/which_one_would_be_better_gemini_15_flash_vs/

**Comment by JuliXBR4VO** [comment]
Here‘s my Instagram: https://www.instagram.com/julixbravo/#
